'use client'

import { useRouter } from 'next/navigation'
import { SectionTitle } from '../ui/SectionTitle'
import { CompanyChip } from '../ui/CompanyChip'
import { Icon } from '../icons/Icon'
import { WAYBILLS, fmtDate } from '../../lib/data'

export function WaybillSection() {
  const router = useRouter()

  return (
    <div className="card" style={{ padding: 24 }}>
      <SectionTitle action={
        <span className="muted" style={{ fontSize: 13 }}>Total generated: {WAYBILLS.length}</span>
      }>
        4. Waybill History
      </SectionTitle>

      <table className="tbl">
        <thead>
          <tr>
            <th>Waybill No.</th>
            <th>Company</th>
            <th>Date</th>
            <th>Supplied To</th>
            <th>Driver</th>
            <th>Generated By</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {WAYBILLS.map(w => (
            <tr
              key={w.id}
              onClick={() => router.push(`/waybills/${w.id}`)}
              style={{ cursor: 'pointer' }}
            >
              <td>
                <span className="t-mono" style={{ fontWeight: 600, color: 'var(--secondary)' }}>
                  {w.number}
                </span>
              </td>
              <td><CompanyChip companyId={w.companyId} /></td>
              <td className="muted" style={{ fontSize: 13, whiteSpace: 'nowrap' }}>{fmtDate(w.date)}</td>
              <td style={{ fontSize: 13 }}>{w.suppliedTo}</td>
              <td className="muted" style={{ fontSize: 13 }}>{w.driverName}</td>
              <td className="muted" style={{ fontSize: 13 }}>{w.generatedBy}</td>
              <td onClick={e => e.stopPropagation()}>
                <button
                  className="btn btn-ghost btn-sm row gap-2"
                  onClick={() => router.push(`/waybills/${w.id}`)}
                >
                  <Icon name="print" size={14} /> Reprint
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
