'use client'

import { useRouter }    from 'next/navigation'
import { SectionTitle } from '../ui/SectionTitle'
import { CompanyChip }  from '../ui/CompanyChip'
import { Icon }         from '../icons/Icon'
import { fmtDate }      from '../../lib/utils'
import type { ReportWaybill } from '@/app/actions/reports'

interface WaybillSectionProps {
  waybills: ReportWaybill[]
}

export function WaybillSection({ waybills }: WaybillSectionProps) {
  const router = useRouter()

  return (
    <div className="card" style={{ padding: 24 }}>
      <SectionTitle action={
        <span className="muted" style={{ fontSize: 13 }}>
          {waybills.length > 0 ? `Last ${waybills.length} shown` : 'None yet'}
        </span>
      }>
        4. Waybill History
      </SectionTitle>

      {waybills.length === 0 ? (
        <div className="muted" style={{ textAlign: 'center', padding: '24px 0', fontSize: 13 }}>
          No waybills generated yet.
        </div>
      ) : (
        <table className="tbl">
          <thead>
            <tr>
              <th>Waybill No.</th>
              <th>Company</th>
              <th>Date</th>
              <th>Supplied To</th>
              <th>Driver</th>
              <th>Generated By</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {waybills.map(w => (
              <tr
                key={w.id}
                onClick={() => router.push(`/waybills/${w.id}`)}
                style={{ cursor: 'pointer' }}
              >
                <td>
                  <span className="t-mono" style={{ fontWeight: 600, color: 'var(--secondary)' }}>
                    {w.number}
                  </span>
                </td>
                <td><CompanyChip code={w.companyCode} name={w.companyName} logoUrl={w.companyLogoUrl} /></td>
                <td className="muted" style={{ fontSize: 13, whiteSpace: 'nowrap' }}>{fmtDate(w.date)}</td>
                <td style={{ fontSize: 13 }}>{w.suppliedTo}</td>
                <td className="muted" style={{ fontSize: 13 }}>{w.driverName}</td>
                <td className="muted" style={{ fontSize: 13 }}>{w.generatedBy}</td>
                <td onClick={e => e.stopPropagation()}>
                  <button
                    className="btn btn-ghost btn-sm row gap-2"
                    onClick={() => router.push(`/waybills/${w.id}`)}
                  >
                    <Icon name="print" size={14} /> View
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}
