'use client'
import { Loading } from '@/components/ui/Loading'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AppShell } from '../../components/layout/AppShell'
import { PageHeader } from '../../components/ui/PageHeader'
import { Icon } from '../../components/icons/Icon'
import { SearchBar } from '../../components/ui/SearchBar'
import { CompanyChip } from '../../components/ui/CompanyChip'
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { WAYBILLS, COMPANIES, fmtDate } from '../../lib/data'

const sorted = [...WAYBILLS].sort(
  (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
)

function WaybillsContent() {
  const router = useRouter()
  const [q, setQ] = useState('')
  const [company, setCompany] = useState('all')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')

  const filtered = useMemo(() => {
    const ql = q.toLowerCase()
    return sorted.filter(w => {
      if (company !== 'all' && w.companyId !== company) return false
      if (from && w.date < from) return false
      if (to && w.date > to) return false
      if (ql && !`${w.number} ${w.suppliedTo}`.toLowerCase().includes(ql)) return false
      return true
    })
  }, [q, company, from, to])

  return (
    <div>
      <PageHeader
        title="Waybills"
        subtitle={`${WAYBILLS.length} waybills issued · auto-incrementing per company per year`}
        actions={
          <>
            <button className="btn btn-secondary btn-sm row gap-2">
              <Icon name="download" size={15} /> Export
            </button>
            <button
              className="btn btn-primary btn-sm row gap-2"
              onClick={() => router.push('/movements/stock-out')}
            >
              <Icon name="plus" size={15} /> New Waybill
            </button>
          </>
        }
      />

      <div className="card" style={{ overflow: 'hidden' }}>
        <div className="row" style={{ padding: 16, borderBottom: '1px solid var(--border)', gap: 12, flexWrap: 'wrap' }}>
          <SearchBar value={q} onChange={setQ} width={320} placeholder="Waybill no. or recipient…" />
          <div className="row gap-2" style={{ marginLeft: 'auto' }}>
            <Select value={company} onValueChange={setCompany}>
              <SelectTrigger className="w-[160px] bg-[#F3F4F6]">
                <SelectValue placeholder="All companies" />
              </SelectTrigger>
              <SelectContent className="bg-white border border-[#E5E7EB] shadow-md">
                <SelectItem value="all">All companies</SelectItem>
                {COMPANIES.map(c => (
                  <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Input
              type="date"
              value={from}
              onChange={e => setFrom(e.target.value)}
              style={{ width: 160 }}
            />
            <span className="muted" style={{ alignSelf: 'center', fontSize: 13 }}>to</span>
            <Input
              type="date"
              value={to}
              onChange={e => setTo(e.target.value)}
              style={{ width: 160 }}
            />
          </div>
        </div>

        <table className="tbl">
          <thead>
            <tr>
              <th>Waybill No.</th>
              <th>Company</th>
              <th>Date</th>
              <th>Supplied To</th>
              <th>Items</th>
              <th>Generated By</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {filtered.map(w => (
              <tr
                key={w.id}
                onClick={() => router.push(`/waybills/${w.id}`)}
                style={{ cursor: 'pointer' }}
              >
                <td>
                  <span className="t-mono" style={{ fontWeight: 600, color: 'var(--secondary)' }}>
                    {w.number}
                  </span>
                </td>
                <td><CompanyChip companyId={w.companyId} /></td>
                <td>
                  <span className="muted" style={{ fontSize: 13, whiteSpace: 'nowrap' }}>
                    {fmtDate(w.date)}
                  </span>
                </td>
                <td style={{ fontSize: 13 }}>{w.suppliedTo}</td>
                <td style={{ fontSize: 13 }}>{w.itemIds.length} line(s)</td>
                <td className="muted" style={{ fontSize: 13 }}>{w.generatedBy}</td>
                <td onClick={e => e.stopPropagation()}>
                  <div className="row gap-2">
                    <button
                      className="btn btn-ghost btn-sm"
                      onClick={() => router.push(`/waybills/${w.id}`)}
                    >
                      <Icon name="eye" size={15} />
                    </button>
                    <button className="btn btn-ghost btn-sm">
                      <Icon name="download" size={15} />
                    </button>
                    <button className="btn btn-ghost btn-sm">
                      <Icon name="print" size={15} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default function WaybillsPage() {
  const router = useRouter()
  const [user, setUser] = useState<{ id: string; name: string; email: string } | null>(null)

  useEffect(() => {
    const stored = localStorage.getItem('auth_user')
    if (!stored) { router.push('/login'); return }
    setUser(JSON.parse(stored))
  }, [router])

  if (!user) return <Loading />

  return (
    <AppShell user={user} onLogout={() => { localStorage.removeItem('auth_user'); router.push('/login') }}>
      <WaybillsContent />
    </AppShell>
  )
}
